# Generated by Django 5.0.4 on 2024-05-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series_id', 'which_season')},
        ),
    ]
