# Generated by Django 5.0.2 on 2024-05-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0002_alter_season_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
    ]
