# Generated by Django 5.0.2 on 2024-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0003_alter_season_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='which_episode',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
