# Generated by Django 5.0.4 on 2024-05-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0005_alter_season_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_of_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.TextField(max_length=500, null=True)),
                ('user_rating', models.IntegerField(default=0)),
                ('review_date', models.DateField(null=True)),
                ('review_like', models.IntegerField(null=True)),
                ('movies_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.movies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='review_of_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.TextField(max_length=500, null=True)),
                ('user_rating', models.IntegerField(default=0)),
                ('review_date', models.DateField(null=True)),
                ('review_like', models.IntegerField(null=True)),
                ('episodes_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.episodes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.user_reg')),
            ],
        ),
    ]
