# Generated by Django 5.0.4 on 2024-05-16 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0007_review_of_series_review_title_comment_of_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlater_of_movies_and_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.movies')),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.series')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.user_reg')),
            ],
        ),
    ]
