# Generated by Django 5.0.4 on 2024-05-16 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0008_watchlater_of_movies_and_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlater_of_movies_and_series',
            name='movies_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.movies'),
        ),
        migrations.AlterField(
            model_name='watchlater_of_movies_and_series',
            name='series_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.series'),
        ),
    ]
