# Generated by Django 5.0.4 on 2024-05-16 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0009_alter_watchlater_of_movies_and_series_movies_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlater_of_movies_and_series',
            name='episode_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.episodes'),
        ),
    ]
