# Generated by Django 5.0.4 on 2024-05-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0010_watchlater_of_movies_and_series_episode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='e_cover_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
