# Generated by Django 5.0.4 on 2024-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0011_episodes_e_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='m_year',
            field=models.IntegerField(default=2024),
        ),
    ]
