# Generated by Django 5.0.4 on 2024-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0012_movies_m_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='m_age',
            field=models.IntegerField(default=16),
        ),
    ]
