# Generated by Django 5.0.4 on 2024-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0013_movies_m_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='m_description',
            field=models.CharField(default='It was good movie........', max_length=1000),
        ),
    ]
