# Generated by Django 5.0.4 on 2024-05-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0014_movies_m_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_plan', models.IntegerField(default=0)),
                ('movies_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.movies')),
                ('series_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.series')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreamNest_app.user_reg')),
            ],
        ),
    ]
