# Generated by Django 5.0.4 on 2024-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamNest_app', '0017_alter_plans_selected_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='m_plan',
            field=models.IntegerField(default=0),
        ),
    ]
